### PR TITLE
Fix cyclic ref

### PR DESCRIPTION
**Pull request by sbcgua**

### CODE REVIEW

**Comment by sbcgua** [comment]
@larshp The exception does not refer to ZIF_AJSON anymore but the error is still there ... looks like some bug. 
image

**Comment by larshp** [comment]
hmm, yea, its broken

**Comment by larshp** [comment]
just disable the rule for now, the interfaces are cyclic anyhow, but will probably work in the merged report

**Comment by sbcgua** [comment]
@larshp Ok, I picked the fix to the master, but left this PR open. Currently it contains just the setting to enable cyclic check, so it can be restarted and merged later when the issue is fixed

**Comment by larshp** [comment]
reported cycle fixed with https://github.com/abaplint/abaplint/pull/2822

**Comment by sbcgua** [comment]
Now it is filter and mapping interfaces, they refer to types defined in `zif_ajson` (`ty_node` in particular). Hmm. Honestly speaking, semantically, the types are in a good place. Yet technically they create a cyclic ref. Maybe it makes sense to separate `ty_node` and Ko to `zif_ajson_types` or similar.

Any serious impact on AG or other tools you maintain ? @larshp @mbtools @albertmink @jrodriguez-rc

**Comment by larshp** [comment]
if its all good, design wise, just exclude one of the interfaces from the rule

**Comment by mbtools** [comment]
Minimal impact on my projects.

**Comment by jrodriguez-rc** [comment]
No impact from my side

**Comment by albertmink** [comment]
No, it is fine.

**Comment by sbcgua** [comment]
Ok, so most of types (except `ty_opts`) were move to `zif_ajson_types`. cyclic_ref rule re-enabled.

Let's hope nothing breaks ... merging

**Pull request merged**
