### PR TITLE
Avoid use of TZNZONE

### PR DESCRIPTION
**Pull request by larshp**
use inline constants instead of referring to data element TZNZONE

### CODE REVIEW

**Comment by sbcgua** [comment]
Problem is that it didn't work on 731 (and 702) - https://github.com/sbcgua/ajson/commit/639e2786493171637c6fe59b82d780b9a79362e3

image

**Comment by sbcgua** [comment]
`lv_tz            type c length 6` seems to work though

**Comment by larshp** [comment]
did the 
```
`UTC` 
```
value work?

**Comment by sbcgua** [comment]
Nope. It really looks like some kind of SAP bug. But ... does not work.
image

**Comment by larshp** [comment]
@sbcgua thanks, try again

**Comment by sbcgua** [comment]
:+1:

**Pull request merged**
