### PR TITLE
Initial timestamp to 0000-00-00T00:00:00Z

### PR DESCRIPTION
**Pull request by jrodriguez-rc**
If the timestamp is initial, it should be converted into 0000-00-00T00:00:00Z, it is not the same that January 1, year 1

### CODE REVIEW

**Comment by sbcgua** [comment]
unit test ?

**Review by sbcgua — CHANGES_REQUESTED** [review]
Could you add unit test pls ?

**Comment by jrodriguez-rc** [comment]
Sure, there're now ready

**Review by sbcgua — APPROVED** [review]
:+1:

**Pull request merged**
