### PR TITLE
cleanup metadata

### PR DESCRIPTION
**Pull request by christianguenter2**
Cleanup thes diffs
grafik

### CODE REVIEW

**Comment by sbcgua** [comment]
hmmm ... and why don't I have this diff in our system ?
Btw I've got a diff after pulling this in ...
image

**Comment by christianguenter2** [comment]
Strange. I have the same diff with abapGit within one of my systems and thought this is an easy fix. Don't have this on other systems.
Closing. I try to investigate further.

**Comment by larshp** [comment]
short texts for sub components added in https://github.com/abapGit/abapGit/pull/5755

**Comment by mbtools** [comment]
We removed the class name from the XML as well. the fix is correct. Reopen and merge it.

PS: Probably AG isn't on the same level in your different systems.

**Comment by sbcgua** [comment]
Hmmm, updating AG on that system is a bit critical. Need stability there :) But OK i'll try to check it later

**Comment by sbcgua** [comment]
Oh well, here it starts on a critical system ... :)
image

image

**Comment by sbcgua** [comment]
OK, I have same diffs after update. Thanks for the hint, merging

**Pull request merged**
