### PR TITLE
New mapper approach

### PR DESCRIPTION
**Pull request by sbcgua**

### CODE REVIEW

**Comment by sbcgua** [comment]
@jrodriguez-rc could you have a look ? This is related to my comments in #112. In a nutshell:
- apply filter only via `create_from`
- simplify the interface respectingly (to_abap/to_json should presumably go away sooner or later)

you initiated the mapper idea and, I assume, using it the most :) so I'd like to know your opinion.

No need to review all the code, and it is not finished anyway. Have a look at readme change, then `zif_ajson_mapping`, then maybe unit tests for what was not clear from the doc.

**Comment by jrodriguez-rc** [comment]
This works only from a JSON source and does a JSON node renaming, isn't it?
I see the changes well but if you allow me some suggestions:
- I'll rename the method to `rename_node` instead of `rename_field` because it is referencing a JSON node, not a field.
- Also, it needs to be implemented into `zcl_ajson_utilities=>merge`

**Comment by jrodriguez-rc** [comment]
`zcl_ajson_utilities=>merge` this method seems to map two JSON. Maybe one is in "lowercase" format and the other in "uppercase" and I want that the resulting JSON has a "lowercase" format.

I wouldn't say I like the implementation of a queue or something like that, anyone can implement the mapping they want

```
CLASS zcl_json_custom_mapping IMPLEMENTATION.

  METHOD zif_ajson_mapping~rename_field.

    DATA(li_upper) = zcl_ajson_mapping=>create_upper_case( ).

    li_upper->rename_field( EXPORTING is_node = is_node
                            CHANGING  cv_name = cv_name ).

    DATA(li_rename) = zcl_ajson_mapping=>create_rename( VALUE #( ( from = 'FIELDNAME1' to = 'FIELDNAME2' ) ) ).

    li_rename->rename_field( EXPORTING is_node = is_node
                             CHANGING  cv_name = cv_name ).

  ENDMETHOD.
```

**Comment by sbcgua** [comment]
... reimplemented to_camel in the new approach and stumbled upon this line
https://github.com/sbcgua/ajson/blob/master/src/zcl_ajson_mapping.clas.locals_imp.abap#L158

@jrodriguez-rc could you please comment what was the idea ?

**Comment by sbcgua** [comment]
I guess it's ready. Let it calm a bit. But generally should be +- final. See the docs for the summary.
- change method name to `rename_node`
- `zcl_ajson_utilities=>merge` - mmm, I don't see an issue, it works with json structure. so it is easy to apply conversion before passing to merge. Also see the next point
- added `clone`, `filter` and `map` methods to the main ajson interface. Thus allowing readable chaining. But introducing circular dependency ... hmmm ...
- "...queue or something...", yeah, makes sense, just implemented it in another way as a "built-in" compound mapper. So now it is possible but does not add weight to the main code

**Comment by sbcgua** [comment]
@larshp BTW there seems to be a minor abaplint bug. It claims that `Statement does not exist in ABAPv702(or a parser error), "cl_abap_unit_assert" (parser_error) [E]`. This happens only for the line with `value #()` which is not 702 of course, yet the cl_abap_unit_assert itself is a false positive. Also there is another message about chaining below. Cannot check on 702 but ... it is not a new syntax afaik

**Pull request merged**
