### PR TITLE
Add set_with_type to writer

### PR DESCRIPTION
**Pull request by mbtools**
Related to #18

### CODE REVIEW

**Comment by sbcgua** [comment]
sorry for delay. Will have a look soon. But quite busy these days :(

**Comment by sbcgua** [comment]
will have a look this weekend, i promise ...

**Comment by mbtools** [comment]
No rush

**Comment by sbcgua** [comment]
OK, so I'm merging it, but I will integrate `set_with_type` into `set`. There seems to be no benefit from a separate method

**Comment by mbtools** [comment]
👍  great. thanks.

**Pull request merged**
