### PR TITLE
Timestamps to_abap

### PR DESCRIPTION
**Pull request by jrodriguez-rc**
Support conversion between json timestamp (2020-07-28T00:00:00Z) to abap (20200728000000)

### CODE REVIEW

**Comment by sbcgua** [comment]
ref #24 
Thanks for the PR, will check it in the near days :+1:

**Review by sbcgua — CHANGES_REQUESTED** [review]
Wow, even with timezones (+-hour) ! Heavy ! 👍 :metal: :sunglasses:

One syntax issue on 731 system
image

**Comment by jrodriguez-rc** [comment]
I use a constant with the requested type for UTC time zone, tested it in 731 😉

**Review by sbcgua — APPROVED** [review]

**Comment by sbcgua** [comment]
Cool. Good feature, thanks !

**Comment by sbcgua** [comment]
BW can I ask you to write a small doc update if you have time ? I think even just an example call would be enough - like with other types

**Comment by jrodriguez-rc** [comment]
Sure, I'll write some examples tomorrow or this weekend

**Pull request merged**
